version: "3.9"

services:
  backend:
    image: tenghuy/app-backend:1.0  
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env  
    ports:
      - "5000:5000"

  frontend:
    image: tenghuy/app-frontend:1.2 
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
